# Generated by Django 3.1.4 on 2021-05-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_studentmarks_studid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
