# Generated by Django 3.1.4 on 2021-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20210528_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.PositiveIntegerField()),
                ('Grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('RollNumber', models.PositiveIntegerField(unique=True)),
                ('DateofBirth', models.DateField()),
            ],
        ),
    ]
