# Generated by Django 3.1.4 on 2021-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentmarks_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
