# Generated by Django 3.1.4 on 2021-05-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_auto_20210528_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('RollNumber', models.PositiveIntegerField(unique=True)),
                ('DateofBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.PositiveIntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentKa', to='api.students')),
            ],
        ),
    ]
